# Generated by Django 5.1 on 2024-08-21 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('duration', models.IntegerField(default=3)),
                ('text_color', models.TextField(default='white')),
                ('bg_color', models.TextField(verbose_name='transparent')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('demo', 'Show Demo'), ('create', 'Create Video')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('generation_options', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='runtext.generation')),
            ],
        ),
    ]
